development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: test_app
  username: postgres
  password: 12345
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: test_app_test
  username: postgres
  password: 12345
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: test_app 
  username: postgres
  password: 12345